rentshop/rentshop/urls.py
# python imports
import datetime

# django imports
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.views.generic import TemplateView

# 3rd party imports
from oscar.app import application
from oscar.core.loading import get_class

# internal imports
abandoned_carts = get_class('basket.views', 'abandoned_carts')
check_cron_view = get_class('partner.views', 'check_cron_view')
state_ajax = get_class('partner.views', 'state_ajax')
city_ajax = get_class('partner.views', 'city_ajax')
search_filter_ajax = get_class('partner.views', 'search_filter_ajax')
get_state_id = get_class('country.views', 'get_state_id')

AdminChangePassword = get_class('dashboard.views', 'AdminChangePassword')
export_combo = get_class('dashboard.combo.combo', 'export_combo')
export_premium = get_class('dashboard.premiumproduct.premium', 'export_premium')
export_individualdb = get_class('dashboard.sales.asp_db', 'export_individualdb')
export_multidb = get_class('dashboard.sales.asp_db', 'export_multidb')
export_menu = get_class('dashboard.manage_menu.combo', 'export_menu')
export_exhibition_menu = get_class('dashboard.manage_menu.combo', 'export_exhibition')
export_quote = get_class('dashboard.sales.best_quote', 'export_quote')
export_tax = get_class('dashboard.taxation.taxation', 'export_tax')
export_percentage = get_class('dashboard.advanced_pay.advanced_pay', 'export_percentage')
export_attribute = get_class('dashboard.attributes.attribute', 'export_attribute')


product_blocked_dates = get_class('catalogue.views', 'product_blocked_dates')
product_blocked_dates_onsubmit = get_class('catalogue.views', 'product_blocked_dates_onsubmit')
send_full_payment_email = get_class('catalogue.views', 'send_full_payment_email')
test_sms = get_class('catalogue.views', 'test_sms')

export_products = get_class('dashboard.views', 'export_products')
export_events = get_class('dashboard.views', 'export_events')
export_bookedevents = get_class('dashboard.sales.sales', 'export_bookedevents')
export_categories = get_class('dashboard.views', 'export_categories')
export_vendors = get_class('dashboard.views', 'export_vendors')
export_customers = get_class('dashboard.views', 'export_customers')
export_users = get_class('dashboard.views', 'export_users')

allocate_vendor_sales = get_class('dashboard.sales.sales', 'allocate_vendor_sales')
vendor_re_allocate = get_class('dashboard.sales.sales', 're_allocate_vendor')
allocate_vendor = get_class('dashboard.sales.best_quote', 'allocate_vendor_best_quote')

export_prime_bucket = get_class('dashboard.sales.sales', 'export_prime_bucket')
export_offers_prime_bucket = get_class('dashboard.sales.sales', 'export_offers_prime_bucket')
get_product_attribute = get_class('dashboard.sales.customized_order', 'get_product_attribute')

update_product = get_class('dashboard.views', 'update_product')
delete_bulk_coupon = get_class('dashboard.views', 'delete_bulk_coupon')
delete_bulk_product = get_class('dashboard.views', 'delete_bulk_product')
delete_product_image = get_class('dashboard.views', 'delete_product_image')
delete_product_attribute = get_class('dashboard.views', 'delete_product_attribute')

get_values_of_attribute = get_class('dashboard.views','get_values_of_attribute')
get_total_price = get_class('catalogue.views','get_total_price')
get_total_price_new = get_class('catalogue.views','get_total_price_new')
set_is_discountable = get_class('catalogue.views','set_is_discountable')
set_product_is_deleted = get_class('catalogue.views','set_product_is_deleted')
order_reminder = get_class('catalogue.views','order_reminder')
delete_bulk_vendor = get_class('dashboard.views', 'delete_bulk_vendor')
delete_bulk_units = get_class('dashboard.views', 'delete_bulk_units')
delete_bulk_user = get_class('dashboard.views', 'delete_bulk_user')
delete_bulk_category = get_class('dashboard.views', 'delete_bulk_category')
delete_bulk_reviews = get_class('dashboard.views', 'delete_bulk_reviews')
delete_bulk_event = get_class('dashboard.views', 'delete_bulk_event')
sales_delete_bulk_event = get_class('dashboard.sales.sales', 'sales_delete_bulk_event')
delete_bulk_season = get_class('dashboard.views', 'delete_bulk_season')
delete_bulk_combo_data = get_class('dashboard.combo.combo', 'delete_bulk_combo_data')
delete_bulk_menu_data = get_class('dashboard.manage_menu.combo', 'delete_bulk_menu_data')

delete_combo_product = get_class('dashboard.views', 'delete_combo_product')
delete_header_product = get_class('dashboard.manage_menu.combo', 'delete_header_product')
delete_header_category = get_class('dashboard.manage_menu.combo', 'delete_header_category')
delete_bulk_exhibition = get_class('dashboard.manage_menu.combo', 'delete_bulk_exhibition_menu_data')

delete_bulk_premium_data = get_class('dashboard.premiumproduct.premium', 'delete_bulk_premium_data')
delete_bulk_individual_data = get_class('dashboard.sales.asp_db', 'delete_bulk_individual_data')
delete_bulk_multi_data = get_class('dashboard.sales.asp_db', 'delete_bulk_multi_data')
delete_bulk_quote_data = get_class('dashboard.sales.best_quote', 'delete_bulk_quote_data')
delete_bulk_tax_data = get_class('dashboard.taxation.taxation', 'delete_bulk_tax_data')
delete_bulk_percentage_data = get_class('dashboard.advanced_pay.advanced_pay', 'delete_bulk_percentage_data')
delete_bulk_attribute_data = get_class('dashboard.attributes.attribute', 'delete_bulk_attribute_data')

export_units = get_class('dashboard.views', 'export_units')
export_season = get_class('dashboard.views', 'export_season')
export_orders = get_class('dashboard.views', 'export_orders')
export_category = get_class('dashboard.views', 'export_category')
export_reviews = get_class('dashboard.views', 'export_reviews')
export_coupon = get_class('dashboard.views', 'export_coupon')
export_low_stock = get_class('dashboard.views', 'export_low_stock')

add_admin_notes = get_class('dashboard.views', 'add_admin_notes')
admin_notes = get_class('dashboard.views', 'admin_notes')
deactivate_note = get_class('dashboard.views', 'deactivate_note')

create_note = get_class('dashboard.notes.notes', 'add_admin_notes')
get_event_products = get_class('dashboard.events.events', 'get_event_products')

payment_cancel = get_class('checkout.views', 'payment_cancel')
payment_success = get_class('checkout.views', 'payment_success')
PaymentCancelView = get_class('checkout.views', 'PaymentCancelView')

test_email = get_class('promotions.views', 'test_email')
update_first_login = get_class('promotions.views', 'update_first_login')
CouponsView = get_class('promotions.views', 'CouponsView')
AboutUs = get_class('promotions.views', 'AboutUs')
ContactUsView = get_class('promotions.views', 'ContactUsView')
TermsPageView = get_class('promotions.views', 'TermsPageView')
FQAView = get_class('promotions.views', 'FQAView')
PoliciesView = get_class('promotions.views', 'PoliciesView')
HWorksView = get_class('promotions.views', 'HWorksView')

email_activate = get_class('customer.views', 'email_activate')
CustomPaymentDetailsView = get_class('checkout.views', 'CustomPaymentDetailsView')
updateVendorPassword = get_class('HeaderMenu.views', 'updateVendorPassword')
load_products = get_class('dashboard.premiumproduct.premium', 'load_products')

individualdb_create = get_class('dashboard.sales.asp_db','CreateIndividualDB')
multidb_create = get_class('dashboard.sales.asp_db','CreateMultiDBModelForm')
find_details = get_class('dashboard.sales.asp_db','find_details')

load_vendors = get_class('dashboard.sales.asp_db','load_vendors')
load_categories = get_class('dashboard.sales.asp_db','load_categories')

get_event_products_rate_card = get_class('dashboard.products.product', 'get_event_products_rate_card')
get_products_for_featured = get_class('dashboard.products.product', 'get_products_for_featured')
add_product_featured = get_class('dashboard.products.product', 'add_product_featured')

get_products_order = get_class('dashboard.sales.customized_order', 'get_products_order')
get_vendors_best_quote = get_class('dashboard.sales.best_quote', 'get_vendors_best_quote')

export_rate_card_products = get_class('dashboard.products.product', 'export_rate_card_products')
delete_bulk_costing_product = get_class('dashboard.products.product', 'delete_bulk_costing_product')
delete_bulk_costing_product_items = get_class('dashboard.products.product', 'delete_bulk_costing_product_items')
remove_featured_product = get_class('dashboard.products.product', 'remove_featured_product')
export_rate_card_products_items = get_class('dashboard.products.product', 'export_rate_card_products_items')
export_featured_products = get_class('dashboard.products.product', 'export_featured_products')
export_distributors = get_class('dashboard.coupon.offers_views', 'export_distributors')
export_price_range_db = get_class('dashboard.coupon.offers_views', 'export_price_range_db')
get_coupondist = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'get_coupondist')
get_coupondetails = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'get_coupondetails')

export_customcoupon_data = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'export_customcoupon_data')

test_email = get_class('partner.views', 'test_email')
welcome_mail = get_class('RentCore.email', 'welcome_mail')
create_pages = get_class('dashboard.accounts.customflatpages', 'CustomFlatPagesCreateUpateView_V1')
get_transaction_details = get_class('checkout.views', 'get_transaction_details')
create_new_cart = get_class('basket.views', 'CreateNewCart')
get_otp = get_class('customer.views', 'get_otp')
get_vendor_otp = get_class('customer.views', 'get_vendor_otp')
verify_otp = get_class('customer.views', 'verify_otp')

delete_price = get_class('dashboard.categoryfilter.categoryfilter', 'delete_price')
delete_price_range = get_class('dashboard.coupon.offers_views', 'delete_price_range')

rentshop/HeaderMenu/models.py
from django.db import models
from oscar.core.loading import get_model

Product = get_model('catalogue', 'Product')
Category = get_model('catalogue', 'Category')


class Admin_Header(models.Model):
    title = models.CharField(max_length=255, blank=True, verbose_name='title')
    is_active = models.BooleanField(default=True)
    sequence_number = models.IntegerField(blank=True,null=True)


    def __str__(self):
        return self.title


class Admin_HeaderMenu(models.Model):
    title_id = models.ForeignKey(Admin_Header, on_delete=models.CASCADE, verbose_name='title_id')
    sub_title = models.CharField(max_length=225, blank=True)
    menu_image = models.ImageField(upload_to='header_menu/', max_length=255,
                                   blank=True, null=True, default='image_not_found.jpg')
    def __str__(self):
        return self.sub_title


class Admin_HeaderSubMenu(models.Model):
    header_menu_id = models.ForeignKey(Admin_HeaderMenu, on_delete=models.CASCADE)
    sub_menu_title = models.CharField(max_length=225, blank=True)
    url = models.CharField(max_length=225, blank=True)
    menu_image = models.ImageField(upload_to='header_menu/',max_length=255,
        blank=True, null=True,default='image_not_found.jpg')

    def __str__(self):
        return self.sub_menu_title

class Manage_Menu(models.Model):
    header_menu = models.ForeignKey(Admin_Header, on_delete=models.CASCADE)
    offer_title =  models.CharField(max_length=225, blank=True)
    product = models.ManyToManyField(Product)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.offer_title

    def get_products_count(self):
        return ManageMenuMasterProducts.objects.filter(manage_menu= self.id, manage_product__is_deleted = False).count()


class ManageMenuMasterProducts(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    manage_menu = models.ForeignKey(
        Manage_Menu, blank=True, null=True,
        related_name='manage_menu', on_delete=models.CASCADE
    )
    manage_product = models.ForeignKey(
        Product, blank=True, null=True,
        related_name='manage_product', on_delete=models.CASCADE
    )

    def __str__(self):

        return str(self.date_created)

class ExhibitionOffers(models.Model):
    header_menu = models.ForeignKey(Admin_Header, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_products_count(self):
        return ExhibitionOffersCategory.objects.filter(manage_menu= self.id, manage_category__depth=1).count()


class ExhibitionOffersCategory(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    manage_menu = models.ForeignKey(
        ExhibitionOffers, blank=True, null=True,
        related_name='exhibition_menu', on_delete=models.CASCADE
    )
    manage_category = models.ForeignKey(
        Category, blank=True, null=True,
        related_name='manage_category', on_delete=models.CASCADE
    )

    def __str__(self):

        return str(self.date_created)

rentshop/templates/dashboard/sales/asp_db/multi_asp/delete.html
{% extends 'dashboard/layout.html' %}

{% load i18n %}

{% block title %}
    Multi ASP Delete | {{ block.super }}
{% endblock %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:asp-db' %}">{% trans "Multi ASP" %}</a>
        </li>
        <li class="active">Delete Multi ASP</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{{ title }}</h2>
    </div>
    <form action="{{ request.GET.urlencode }}" method="post" class="well" id="form">
        {% csrf_token %}
        <p style="font-size:18px;">Are you really want to delete this Multi ASP?</p>
        <div class="form-actions">
            <input type="hidden" value="{{product.id}}" name="product_id">
            <button type="button" onclick="confirm_multi_delete()" class="btn btn-danger">{% trans "Delete" %}</button>
            {% trans "or" %}
            <a href="{% url 'dashboard:asp-db' %}">{% trans "cancel" %}</a>
        </div>
    </form>
{% endblock %}

{% load static %}
{% block extrascripts %}
    {{ block.super }}
    <script>
        function confirm_multi_delete(){
            var is_confirm = confirm("Do you really want to delete this record.");
            if (is_confirm == false){
                return false;
            }
            $('#form').submit();
        }
    </script>
{% endblock %}

rentshop/templates/dashboard/sales/asp_db/multi_asp/details.html
{% extends 'dashboard/layout.html' %}
{% load sorting_tags %}
{% load i18n %}

{% block title %}
    {% trans "Multi Database" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active"> <a href="{% url 'dashboard:asp-db' %}">{% trans "Multi Database" %}</a></li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header">
        <h1>{% trans "Multi Database" %}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <form action="." method="post" class="order_table">
        {% csrf_token %}
        <table class="table table-bordered">
            <caption>
                <em class="icon-briefcase icon-large"></em> Multi DB Details
                <span id="selected_mark" class="selection_mark label label-default"></span>
                <input type="hidden" id="ids_ev_list">
            </caption>
            {% if multi %}
                <tr>
                    <th colspan="5" style="text-align:center">Category</th>
                </tr>
                <tr>
                    <td colspan="5" style="text-align:center">{{multi.category}}</td>
                </tr>
                <tr>
                    <th colspan="5" style="text-align:center">Frontliener ASP</th>
                </tr>
                <tr>
                    <th style="text-align:center">Sr. No.</th>
                    <th>Name</th>
                    <th>Area</th>
                    <th>Mobile No. 1</th>
                    <th>Mobile No. 2</th>

                </tr>
            {% for vendor in multi.frontliener.all %}
            <tr>

                    <td style="text-align:center">{{ forloop.counter }}</td>
                    <td>{{vendor.name}}</td>
                    <td>{{vendor.address_line_1}}</td>
                    <td>{{vendor.telephone_number}}</td>
                    <td>{{vendor.alternate_mobile_number}}</td>

            </tr>
            {% endfor %}
                <tr>
                     <th colspan="5" style="text-align:center">Backup1 ASP</th>
                </tr>
            <tr>
                <th style="text-align:center">Sr. No.</th>
                    <th>Name</th>
                    <th>Area</th>
                    <th>Mobile No. 1</th>
                    <th>Mobile No. 2</th>
            </tr>
            {% for vendor in multi.backup1.all %}
            <tr>

                    <td style="text-align:center">{{ forloop.counter }}</td>
                    <td>{{vendor.name}}</td>
                    <td>{{vendor.address_line_1}}</td>
                    <td>{{vendor.telephone_number}}</td>
                    <td>{{vendor.alternate_mobile_number}}</td>

            </tr>
             {% endfor %}
            <tr>
                 <th colspan="5" style="text-align:center">Backup2 ASP</th>
            </tr>

            <tr>
                <th style="text-align:center">Sr. No.</th>
                    <th>Name</th>
                    <th>Area</th>
                    <th>Mobile No. 1</th>
                    <th>Mobile No. 2</th>
            </tr>
            {% for vendor in multi.backup2.all %}
            <tr>

                <td style="text-align:center">{{ forloop.counter }}</td>
                    <td>{{vendor.name}}</td>
                    <td>{{vendor.address_line_1}}</td>
                    <td>{{vendor.telephone_number}}</td>
                    <td>{{vendor.alternate_mobile_number}}</td>

            </tr>
{% endfor %}
            {% else %}
                <tr><td>{% trans "No record found." %}</td></tr>
            {% endif %}
        </table>
        {% include "dashboard/partials/pagination.html" %}
    </form>
{% endblock dashboard_content %}

{% load static %}
{% block extrascripts %}
    {{ block.super }}
    <script>

        function export_prime_bucket(url, order_number){

            var checked_id = [];
            $.each($("input[class='selected_event']:checked"), function(){
                checked_id.push($(this).val());
            });

            var _url = url+'?&order_number='+order_number;
            document.location.href = _url;

        }



$('#master_event').change(function (){

    $('.selected_event:checkbox').not(this).prop('checked', this.checked);

    var selected_ids = $('.selected_event:checked').map(function(){
        return $(this).val();
    });

    if (selected_ids.length == 0){
        $('#selected_mark').html('')
    }else{
        $('#selected_mark').html('Total '+selected_ids.length+ ' event selected.')
    }

});

$('.selected_event').change(function (){

    $('#master_event').prop('checked', false);

    var selected_ids = $('.selected_event:checked').map(function(){
        return $(this).val();
    });

    if (selected_ids.length == 0){
        $('#selected_mark').html('')
    }else{
        $('#selected_mark').html('Total '+selected_ids.length+ ' event selected.')
    }

});

    </script>
<script>

function get_type() {
  alert("The input value has changed. The new value is: ");
  var type_value = $("#id_type").val();
        if(type_value == 'INDIVIDUAL')
            {
               $("#catform").attr("action", "/create_individual_db/");
             }
             else{
             $("#catform").attr("action", "/create_multi_db/");
             }

}
    function create_abp(ul,category, type){
            console.log(category);
            console.log(type);
            var url='';
            if(type == 'INDIVIDUAL')
            {
                url= '/create_individual_db/';
             }
             else{
             url =  '/create_multi_db/';
             }
             alert(ul);
            var _url = ul+'?&category='+category;
            alert(_url);
            document.location.href = _url;
        }
</script>
{% endblock %}

rentshop/templates/dashboard/sales/asp_db/multi_asp/form.html
{% extends 'dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {{ title }} | {% trans "Multi ASP" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:asp-db' %}">Multi ASP</a>
        </li>

    <li class="active">{% trans "Edit" %}</li>
    </ul>
{% endblock %}

{% block headertext %}Multi ASP{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-money icon-large"></i>
            {% if form.instance %}
                Edit Multi ASP
            {% else %}
                Create Multi ASP
            {% endif %}
        </h2>
    </div>
    <form action="." method="post" class="well form-stacked">
        {% csrf_token %}
        {% include "dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary btn-lg" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:asp-db' %}" class="btn btn-default">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}

{% block extrascripts %}
    {{ block.super }}

<script>
    function get_vendors(){
            var category_id = $('#id_category').val();
            //alert(category_id);
            $.ajax({
                url: '/load_vendors',
                data: {
                  'category_id': category_id
                },
                success: function (data) {
                    $("#id_frontliener").html(data);
                    $("#id_backup1").html(data);
                    $("#id_backup2").html(data);
                }
            });
        }
<!--$(document).ready(function () {-->
<!--    var category_id = $('#id_category').val();-->
<!--          alert(category_id);-->
<!--            $.ajax({-->
<!--                url: '/load_vendors',-->
<!--                data: {-->
<!--                  'category_id': category_id-->
<!--                },-->
<!--                success: function (data) {-->
<!--                    $("#id_frontliener").html(data);-->
<!--                    $("#id_backup1").html(data);-->
<!--                    $("#id_backup2").html(data);-->
<!--                }-->
<!--            });-->
<!--     });-->

</script>
<script>

    $('#id_frontliener').change(function(){
    var selectedItem = $('#id_frontliener').val();
    var category_id = $('#id_category').val();
   // alert(selectedItem);
     $.ajax({
                url: '/load_backup1',
                data: {
                  'category_id': category_id,
                  'selectedItem':selectedItem,
                },
                success: function (data) {
                    $("#id_frontliener").html(data);
                    $("#id_backup1").html(data);
                    $("#id_backup2").html(data);
                }
            });
    });
</script>

{% endblock %}

rentshop/templates/dashboard/sales/asp_db/multi_asp/update_form.html
{% extends 'dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {{ title }} | {% trans "Multi ASP" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:asp-db' %}">Multi ASP</a>
        </li>

    <li class="active">{% trans "Edit" %}</li>
    </ul>
{% endblock %}

{% block headertext %}Multi ASP{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-money icon-large"></i>
            {% if form.instance %}
                Edit Multi ASP
            {% else %}
                Create Multi ASP
            {% endif %}
        </h2>
    </div>
    <form action="." method="post" class="well form-stacked">
        {% csrf_token %}
        {% include "dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary btn-lg" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:asp-db' %}" class="btn btn-default">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}

{% block extrascripts %}
    {{ block.super }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
    function get_vendors(){
            var category_id = $('#id_category').val();
           // alert(category_id);
            $.ajax({
                url: '/load_vendors',
                data: {
                  'category_id': category_id
                },
                success: function (data) {
                    $("#id_frontliener").html(data);
                    $("#id_backup1").html(data);
                    $("#id_backup2").html(data);
                }
            });
        }
        $(document).ready(function() {
               $('#id_frontliener').select2(
               {
               mulitple:true;
               });
               $('#id_backup1').select2();
               $('#id_backup2').select2();
        });
</script>
{% endblock %}