rentshop/rentshop/urls.py
# python imports
import datetime

# django imports
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.views.generic import TemplateView

# 3rd party imports
from oscar.app import application
from oscar.core.loading import get_class

# internal imports
abandoned_carts = get_class('basket.views', 'abandoned_carts')
check_cron_view = get_class('partner.views', 'check_cron_view')
state_ajax = get_class('partner.views', 'state_ajax')
city_ajax = get_class('partner.views', 'city_ajax')
search_filter_ajax = get_class('partner.views', 'search_filter_ajax')
get_state_id = get_class('country.views', 'get_state_id')

AdminChangePassword = get_class('dashboard.views', 'AdminChangePassword')
export_combo = get_class('dashboard.combo.combo', 'export_combo')
export_premium = get_class('dashboard.premiumproduct.premium', 'export_premium')
export_individualdb = get_class('dashboard.sales.asp_db', 'export_individualdb')
export_multidb = get_class('dashboard.sales.asp_db', 'export_multidb')
export_menu = get_class('dashboard.manage_menu.combo', 'export_menu')
export_exhibition_menu = get_class('dashboard.manage_menu.combo', 'export_exhibition')
export_quote = get_class('dashboard.sales.best_quote', 'export_quote')
export_tax = get_class('dashboard.taxation.taxation', 'export_tax')
export_percentage = get_class('dashboard.advanced_pay.advanced_pay', 'export_percentage')
export_attribute = get_class('dashboard.attributes.attribute', 'export_attribute')


product_blocked_dates = get_class('catalogue.views', 'product_blocked_dates')
product_blocked_dates_onsubmit = get_class('catalogue.views', 'product_blocked_dates_onsubmit')
send_full_payment_email = get_class('catalogue.views', 'send_full_payment_email')
test_sms = get_class('catalogue.views', 'test_sms')

export_products = get_class('dashboard.views', 'export_products')
export_events = get_class('dashboard.views', 'export_events')
export_bookedevents = get_class('dashboard.sales.sales', 'export_bookedevents')
export_categories = get_class('dashboard.views', 'export_categories')
export_vendors = get_class('dashboard.views', 'export_vendors')
export_customers = get_class('dashboard.views', 'export_customers')
export_users = get_class('dashboard.views', 'export_users')

allocate_vendor_sales = get_class('dashboard.sales.sales', 'allocate_vendor_sales')
vendor_re_allocate = get_class('dashboard.sales.sales', 're_allocate_vendor')
allocate_vendor = get_class('dashboard.sales.best_quote', 'allocate_vendor_best_quote')

export_prime_bucket = get_class('dashboard.sales.sales', 'export_prime_bucket')
export_offers_prime_bucket = get_class('dashboard.sales.sales', 'export_offers_prime_bucket')
get_product_attribute = get_class('dashboard.sales.customized_order', 'get_product_attribute')

update_product = get_class('dashboard.views', 'update_product')
delete_bulk_coupon = get_class('dashboard.views', 'delete_bulk_coupon')
delete_bulk_product = get_class('dashboard.views', 'delete_bulk_product')
delete_product_image = get_class('dashboard.views', 'delete_product_image')
delete_product_attribute = get_class('dashboard.views', 'delete_product_attribute')

get_values_of_attribute = get_class('dashboard.views','get_values_of_attribute')
get_total_price = get_class('catalogue.views','get_total_price')
get_total_price_new = get_class('catalogue.views','get_total_price_new')
set_is_discountable = get_class('catalogue.views','set_is_discountable')
set_product_is_deleted = get_class('catalogue.views','set_product_is_deleted')
order_reminder = get_class('catalogue.views','order_reminder')
delete_bulk_vendor = get_class('dashboard.views', 'delete_bulk_vendor')
delete_bulk_units = get_class('dashboard.views', 'delete_bulk_units')
delete_bulk_user = get_class('dashboard.views', 'delete_bulk_user')
delete_bulk_category = get_class('dashboard.views', 'delete_bulk_category')
delete_bulk_reviews = get_class('dashboard.views', 'delete_bulk_reviews')
delete_bulk_event = get_class('dashboard.views', 'delete_bulk_event')
sales_delete_bulk_event = get_class('dashboard.sales.sales', 'sales_delete_bulk_event')
delete_bulk_season = get_class('dashboard.views', 'delete_bulk_season')
delete_bulk_combo_data = get_class('dashboard.combo.combo', 'delete_bulk_combo_data')
delete_bulk_menu_data = get_class('dashboard.manage_menu.combo', 'delete_bulk_menu_data')

delete_combo_product = get_class('dashboard.views', 'delete_combo_product')
delete_header_product = get_class('dashboard.manage_menu.combo', 'delete_header_product')
delete_header_category = get_class('dashboard.manage_menu.combo', 'delete_header_category')
delete_bulk_exhibition = get_class('dashboard.manage_menu.combo', 'delete_bulk_exhibition_menu_data')

delete_bulk_premium_data = get_class('dashboard.premiumproduct.premium', 'delete_bulk_premium_data')
delete_bulk_individual_data = get_class('dashboard.sales.asp_db', 'delete_bulk_individual_data')
delete_bulk_multi_data = get_class('dashboard.sales.asp_db', 'delete_bulk_multi_data')
delete_bulk_quote_data = get_class('dashboard.sales.best_quote', 'delete_bulk_quote_data')
delete_bulk_tax_data = get_class('dashboard.taxation.taxation', 'delete_bulk_tax_data')
delete_bulk_percentage_data = get_class('dashboard.advanced_pay.advanced_pay', 'delete_bulk_percentage_data')
delete_bulk_attribute_data = get_class('dashboard.attributes.attribute', 'delete_bulk_attribute_data')

export_units = get_class('dashboard.views', 'export_units')
export_season = get_class('dashboard.views', 'export_season')
export_orders = get_class('dashboard.views', 'export_orders')
export_category = get_class('dashboard.views', 'export_category')
export_reviews = get_class('dashboard.views', 'export_reviews')
export_coupon = get_class('dashboard.views', 'export_coupon')
export_low_stock = get_class('dashboard.views', 'export_low_stock')

add_admin_notes = get_class('dashboard.views', 'add_admin_notes')
admin_notes = get_class('dashboard.views', 'admin_notes')
deactivate_note = get_class('dashboard.views', 'deactivate_note')

create_note = get_class('dashboard.notes.notes', 'add_admin_notes')
get_event_products = get_class('dashboard.events.events', 'get_event_products')

payment_cancel = get_class('checkout.views', 'payment_cancel')
payment_success = get_class('checkout.views', 'payment_success')
PaymentCancelView = get_class('checkout.views', 'PaymentCancelView')

test_email = get_class('promotions.views', 'test_email')
update_first_login = get_class('promotions.views', 'update_first_login')
CouponsView = get_class('promotions.views', 'CouponsView')
AboutUs = get_class('promotions.views', 'AboutUs')
ContactUsView = get_class('promotions.views', 'ContactUsView')
TermsPageView = get_class('promotions.views', 'TermsPageView')
FQAView = get_class('promotions.views', 'FQAView')
PoliciesView = get_class('promotions.views', 'PoliciesView')
HWorksView = get_class('promotions.views', 'HWorksView')

email_activate = get_class('customer.views', 'email_activate')
CustomPaymentDetailsView = get_class('checkout.views', 'CustomPaymentDetailsView')
updateVendorPassword = get_class('HeaderMenu.views', 'updateVendorPassword')
load_products = get_class('dashboard.premiumproduct.premium', 'load_products')

individualdb_create = get_class('dashboard.sales.asp_db','CreateIndividualDB')
multidb_create = get_class('dashboard.sales.asp_db','CreateMultiDBModelForm')
find_details = get_class('dashboard.sales.asp_db','find_details')

load_vendors = get_class('dashboard.sales.asp_db','load_vendors')
load_categories = get_class('dashboard.sales.asp_db','load_categories')

get_event_products_rate_card = get_class('dashboard.products.product', 'get_event_products_rate_card')
get_products_for_featured = get_class('dashboard.products.product', 'get_products_for_featured')
add_product_featured = get_class('dashboard.products.product', 'add_product_featured')

get_products_order = get_class('dashboard.sales.customized_order', 'get_products_order')
get_vendors_best_quote = get_class('dashboard.sales.best_quote', 'get_vendors_best_quote')

export_rate_card_products = get_class('dashboard.products.product', 'export_rate_card_products')
delete_bulk_costing_product = get_class('dashboard.products.product', 'delete_bulk_costing_product')
delete_bulk_costing_product_items = get_class('dashboard.products.product', 'delete_bulk_costing_product_items')
remove_featured_product = get_class('dashboard.products.product', 'remove_featured_product')
export_rate_card_products_items = get_class('dashboard.products.product', 'export_rate_card_products_items')
export_featured_products = get_class('dashboard.products.product', 'export_featured_products')
export_distributors = get_class('dashboard.coupon.offers_views', 'export_distributors')
export_price_range_db = get_class('dashboard.coupon.offers_views', 'export_price_range_db')
get_coupondist = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'get_coupondist')
get_coupondetails = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'get_coupondetails')

export_customcoupon_data = get_class('dashboard.coupon.customize_coupon.customize_coupon', 'export_customcoupon_data')

test_email = get_class('partner.views', 'test_email')
welcome_mail = get_class('RentCore.email', 'welcome_mail')
create_pages = get_class('dashboard.accounts.customflatpages', 'CustomFlatPagesCreateUpateView_V1')
get_transaction_details = get_class('checkout.views', 'get_transaction_details')
create_new_cart = get_class('basket.views', 'CreateNewCart')
get_otp = get_class('customer.views', 'get_otp')
get_vendor_otp = get_class('customer.views', 'get_vendor_otp')
verify_otp = get_class('customer.views', 'verify_otp')

delete_price = get_class('dashboard.categoryfilter.categoryfilter', 'delete_price')
delete_price_range = get_class('dashboard.coupon.offers_views', 'delete_price_range')

rentshop/HeaderMenu/models.py
from django.db import models
from oscar.core.loading import get_model

Product = get_model('catalogue', 'Product')
Category = get_model('catalogue', 'Category')


class Admin_Header(models.Model):
    title = models.CharField(max_length=255, blank=True, verbose_name='title')
    is_active = models.BooleanField(default=True)
    sequence_number = models.IntegerField(blank=True,null=True)


    def __str__(self):
        return self.title


class Admin_HeaderMenu(models.Model):
    title_id = models.ForeignKey(Admin_Header, on_delete=models.CASCADE, verbose_name='title_id')
    sub_title = models.CharField(max_length=225, blank=True)
    menu_image = models.ImageField(upload_to='header_menu/', max_length=255,
                                   blank=True, null=True, default='image_not_found.jpg')
    def __str__(self):
        return self.sub_title


class Admin_HeaderSubMenu(models.Model):
    header_menu_id = models.ForeignKey(Admin_HeaderMenu, on_delete=models.CASCADE)
    sub_menu_title = models.CharField(max_length=225, blank=True)
    url = models.CharField(max_length=225, blank=True)
    menu_image = models.ImageField(upload_to='header_menu/',max_length=255,
        blank=True, null=True,default='image_not_found.jpg')

    def __str__(self):
        return self.sub_menu_title

class Manage_Menu(models.Model):
    header_menu = models.ForeignKey(Admin_Header, on_delete=models.CASCADE)
    offer_title =  models.CharField(max_length=225, blank=True)
    product = models.ManyToManyField(Product)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.offer_title

    def get_products_count(self):
        return ManageMenuMasterProducts.objects.filter(manage_menu= self.id, manage_product__is_deleted = False).count()


class ManageMenuMasterProducts(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    manage_menu = models.ForeignKey(
        Manage_Menu, blank=True, null=True,
        related_name='manage_menu', on_delete=models.CASCADE
    )
    manage_product = models.ForeignKey(
        Product, blank=True, null=True,
        related_name='manage_product', on_delete=models.CASCADE
    )

    def __str__(self):

        return str(self.date_created)

class ExhibitionOffers(models.Model):
    header_menu = models.ForeignKey(Admin_Header, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_products_count(self):
        return ExhibitionOffersCategory.objects.filter(manage_menu= self.id, manage_category__depth=1).count()


class ExhibitionOffersCategory(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    manage_menu = models.ForeignKey(
        ExhibitionOffers, blank=True, null=True,
        related_name='exhibition_menu', on_delete=models.CASCADE
    )
    manage_category = models.ForeignKey(
        Category, blank=True, null=True,
        related_name='manage_category', on_delete=models.CASCADE
    )

    def __str__(self):

        return str(self.date_created)

rentshop/templates/catalogue/reviews/review_detail.html
{% extends "layout.html" %}
{% load i18n %}

{% block title %}
    {{ review.title }} | {% trans "Reviews" %} | {{ product.title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans "Home" %}</a>
        </li>
        {% with category=product.categories.all.0 %}
            {% for c in category.get_ancestors_and_self %}
                <li>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
            <li>
                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
            </li>
            <li>
                <a href="{% url 'catalogue:reviews-list' product_slug=product.slug product_pk=product.pk %}">{% trans "Reviews" %}</a>
            </li>
        {% endwith %}
        <li class="active">{{ review.title }}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {% trans "Customer reviews" %}
{% endblock  %}

{% block content %}
    <section>
        {% include 'catalogue/reviews/review_product.html' %}
        {% include 'catalogue/partials/review.html' %}
    </section>
{% endblock %}

rentshop/templates/catalogue/reviews/review_form.html
{% extends "catalogue/detail.html" %}
{% load i18n %}
{% block product_review %}

<style>
    .reviews_tab{display:none !important;
    }
    .description_tab,.additional_information_tab{
        width:50% !important;
    }
    .btn-review{
        text-transform: capitalize;
        width:80px !important;
    }
    .btn-default{
        background-color: #eddbdb;
    }
    .form-control:focus{
        border: 1px solid #e0e0e0 !important;
    }
    #id_title, #id_captcha_1{
        text-align: left;
    }
    #id_captcha_1{
        margin-top:15px;
    }
</style>

<div class="shop-layout-wrap active" id="nz-target" style="padding:0;" autofocus>
    <section class='content nz-clearfix' id="id_review_div" data-rp="true" data-rpn="4">
        <div class="nz-shop-posts nz-clearfix">
            <section class="main-content" style="width:100%">
                <form id="add_review_form" class="" method="post" action="./#addreview" style="padding: 70px 50px;background-color: #fff;">
                    <fieldset>
                        <legend>{% trans "Leave a product review" %}</legend>
                        {% csrf_token %}
                        {% include 'partials/form_field.html' with field=form.title %}
                        <div class="reviewrating form-group {% if form.score.errors %}error{% endif %}">

                            <label for="{{ form.score.auto_id }}" class="control-label required">
                                <span>Rating <em style="color:red">*</em></span>
                            </label>

                            <div class="controls">

                                <div class="form-group" id="rating-ability-wrapper">
                                    <label class="control-label" for="rating">
                                        <input type="hidden" id="selected_rating" name="score" value="" required="required">
                                    </label>

                                    <button type="button" class="btnrating btn btn-default btn-lg" data-attr="1" id="rating-star-1">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </button>
                                    <button type="button" class="btnrating btn btn-default btn-lg" data-attr="2" id="rating-star-2">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </button>
                                    <button type="button" class="btnrating btn btn-default btn-lg" data-attr="3" id="rating-star-3">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </button>
                                    <button type="button" class="btnrating btn btn-default btn-lg" data-attr="4" id="rating-star-4">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </button>
                                    <button type="button" class="btnrating btn btn-default btn-lg" data-attr="5" id="rating-star-5">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </button>
                                </div>

                                {% for error in form.score.errors %}
                                    <span class="error-block" style="color: red;">
                                        <em class="icon-exclamation-sign"></em> {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                            {% comment %}
                                {% include 'partials/form_field.html' with field=form.score %}
                            {% endcomment %}
                        </div>

                        {% include 'partials/form_field.html' with field=form.body %}
                        <span id="errMsg"></span>
                        {% if form.name %}
                            {% include 'partials/form_field.html' with field=form.name %}
                        {% endif %}
                        {% if form.email %}
                            {% include 'partials/form_field.html' with field=form.email %}
                        {% endif %}

                        <p style="color:#000;">
                            <strong>Captcha <em style="color:red">*</em></strong>
                        </p>
                        {{form.captcha}}
                        {% if form.errors.captcha %}
                            <span class="error-block" style="color: red;">
                                <em class="icon-exclamation-sign"></em> {{form.errors.captcha.as_text}}
                            </span>
                            <br/><br/>
                        {% endif %}

                        <button type="submit" class="btn btn-yellow btn-red btn-review" data-loading-text="{% trans 'Saving...' %}">{% trans "Submit" %}</button>

                        <a href="{{ product.get_absolute_url }}" class="btn btn-review btn-yellow btn-red">{% trans "Cancel" %}</a>
                    </fieldset>
                </form>
            </section>
        </div>
    </section>
</div>

{% load static %}

{% block extrascripts %}
{{ block.super }}

<script src="{% static 'oscar/js/product/ratings.js' %}"></script>

<script>

$(document).ready( function() {
    var maxLen = 150;
    $("#id_body").attr('maxlength','150');
    $('#id_body').keypress(function(event){
        var Length = $("#id_body").val().length;
        if (Length >= maxLen){
             $('#errMsg').text('Please enter comment in less than 150 characters.');
        }else{
            $('#errMsg').text('');
        }
    });

 });

</script>

{% endblock %}
{% endblock %}

rentshop/templates/catalogue/reviews/review_list.html
{% extends "layout.html" %}

{% load history_tags %}
{% load i18n %}

{% block title %}
    {% trans "All reviews" %} | {{ product.title }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans "Home" %}</a>
        </li>
        {% with category=product.categories.all.0 %}
            {% for c in category.get_ancestors_and_self %}
                <li>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
            <li>
                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
            </li>
        {% endwith %}
        <li class="active">{% trans "All reviews" %}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {% trans "Customer reviews" %}
{% endblock  %}

{% block content %}

    <section>        
        {% include 'catalogue/reviews/review_product.html' %}

        {% if reviews %}
            <form action="." method="get" class="form-inline">
                {% for field in form %}
                    {{ field.label }}
                    {{ field }}
                {% endfor %}
                <input type="submit" class="btn btn-default" value="{% trans "Go" %}" />
            </form>

            {% for review in reviews %}
                {% include 'catalogue/partials/review.html' %}
            {% endfor %}
            {% include 'partials/pagination.html' %}

        {% else %}
            <p>{% trans "This product does not have any reviews yet." %}</p>
        {% endif %}

    </section>
{% endblock %}

rentshop/templates/catalogue/reviews/review_product.html
{% load thumbnail %}
{% load staticfiles %}

<div class="row">
    <div class="col-sm-2">
        <div class="image_container">
            {% with image=product.primary_image %}
                {% thumbnail image.original "x155" upscale=False as thumb %}
                    <a href="{{ product.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ product.get_title }}" class="thumbnail"></a>
                {% empty %}
            <a href="{{ product.get_absolute_url }}"><img src="{{ image.original.url }}" alt="{{ product.get_title }}" class="thumbnail"></a>
                {% endthumbnail %}
            {% endwith %}
        </div>
    </div>
    <div class="col-sm-10">
        <h2><a href="{{ product.get_absolute_url }}">{{ product.get_title }}</a></h2>
        {% include "catalogue/partials/stock_record.html" %}
        {% include "catalogue/reviews/partials/review_stars.html" %}
    </div>
</div>

<hr>